import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Syne } from 'next/font/google'

const syne = Syne({ subsets: ['latin'], weight: ['500'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='max-h-screen max-w-screen'>
      <body className={`${syne.className} bg-[#fffff] m-0 p-0 `}>
        
        {children
        }</body>
    </html>
  )
}
